In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.special import erf
import astropy.units as unit
import astropy.constants as const
import itertools
import plotly.express as px 
import pandas as pd

from axion_functions import *

In [15]:
bg = np.loadtxt("..\\cosmo_bg.txt")

days = bg[0,:]
bg_rates = bg[1,:]
bg_base = 5.2e-1

bg_total = bg_base + bg_rates

cpd_to_count = 365.25*3*50
cpd_to_ckg = 50*5
N_bg = bg_total*cpd_to_count*5

def make_timely_counts():
    """Ends up in counts per kev"""
    output = []
    for index in range(len(days)-1):
        val = np.trapz(bg_total[:index], days[:index])*50
        output.append(val)
    return np.array(output)

bg_total[-1]

0.5825

In [11]:
annual_df = pd.read_csv("annual_changes_mass.csv", index_col=0)
annual_df #g=1.23e-10
mean_123 = np.mean(annual_df["1"]/(2*np.pi))
mean_123_5 = np.mean(annual_df["5"]/(2*np.pi))
mean_123_10 = np.mean(annual_df["10"]/(2*np.pi))

In [16]:
N_bg_time = make_timely_counts()*7
n_req = 1.96*np.sqrt(N_bg_time)/0.9574230753375434 #Divide by fraction within energy range
n_req/cpd_to_count

array([0.        , 0.        , 0.00435376, 0.00563891, 0.00656395,
       0.00733447, 0.00801039, 0.00867716, 0.00917708, 0.00969407,
       0.01017765, 0.01063376, 0.01106646, 0.01147903, 0.0118742 ,
       0.01225394, 0.01262003, 0.01297389, 0.01331682, 0.0136498 ,
       0.01397368, 0.01428926, 0.01459716, 0.01489794, 0.01519208,
       0.01548005, 0.01576223, 0.01603895, 0.01631056, 0.01657732,
       0.01683949, 0.01709732, 0.01735101, 0.01760076, 0.01784675,
       0.01808913, 0.01832807, 0.01856371, 0.01879617, 0.01902557,
       0.01925205, 0.01947571, 0.01969665, 0.01991494, 0.02013071,
       0.02034403, 0.02055497, 0.02076363, 0.02097005, 0.02117431,
       0.02137648, 0.02157662, 0.02177478, 0.02197103, 0.0221654 ,
       0.02235797, 0.02254878, 0.02273786, 0.02292527, 0.02311105])

In [17]:
days

array([   0.,   30.,   60.,   90.,  120.,  150.,  183.,  210.,  240.,
        270.,  300.,  330.,  360.,  390.,  420.,  450.,  480.,  510.,
        540.,  570.,  600.,  630.,  660.,  690.,  720.,  750.,  780.,
        810.,  840.,  870.,  900.,  930.,  960.,  990., 1020., 1050.,
       1080., 1110., 1140., 1170., 1200., 1230., 1260., 1290., 1320.,
       1350., 1380., 1410., 1440., 1470., 1500., 1530., 1560., 1590.,
       1620., 1650., 1680., 1710., 1740., 1770., 1800.])

In [18]:
np.argwhere(days == 1800)

array([[60]], dtype=int64)

In [19]:
n_req[59]

1266.1966246316108

In [20]:
(n_req[59]/(mean_123_10*5/3))**(1/4)*1.23e-10

1.1568085213306196e-09